version: '3'
services:
  gateway:
    image: kcollins/ignition:7.9.12
    volumes:
      - gateway_data:/var/lib/ignition
      - x11:/tmp/.X11-unix
    ports:
      - 8088:8088
    stop_grace_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  xvfb:
    image: kcollins/xvfb:latest
    volumes:
      - x11:/tmp/.X11-unix


volumes:
  gateway_data:
  x11: