version: "3"
services:
  hub:
    image: kcollins/ignition:latest  # You can change `latest` to a specific version, e.g. `8.0.5`
    ports:
      - "8088:8088"
    volumes:
      # - ./gateway_backup.gwbk:/restore.gwbk
      - hub_data:/var/lib/ignition
    environment:
      GATEWAY_SYSTEM_NAME: hub
      GATEWAY_ADMIN_PASSWORD: password
      GATEWAY_NETWORK_AUTOACCEPT_DELAY: 120

  spoke1:
    image: kcollins/ignition:latest
    ports:
      - "8089:8088"
    volumes:
      # - ./gateway_backup.gwbk:/restore.gwbk
      - spoke1_data:/var/lib/ignition
    environment:
      GATEWAY_SYSTEM_NAME: spoke1
      GATEWAY_ADMIN_PASSWORD: password
      GATEWAY_NETWORK_0_HOST: hub

  spoke2:
    image: kcollins/ignition:latest-edge
    ports:
      - "8090:8088"
    volumes:
      - spoke2_data:/var/lib/ignition
    environment:
      GATEWAY_SYSTEM_NAME: spoke2
      GATEWAY_ADMIN_PASSWORD: password
      GATEWAY_NETWORK_0_HOST: hub
    

volumes:
  hub_data:
  spoke1_data:
  spoke2_data: